name: auge
description: Autogestão
version: 0.0.1
#homepage: https://www.example.com
#author: Administrador <email@example.com>

environment:
  sdk: '>=2.0.0-dev.3.0 <2.0.0'

dependencies:
  angular: 5.0.0-alpha+4
  angular_components: 0.9.0-alpha+3
  angular_forms: 1.0.1-alpha+4
  angular_router: ^2.0.0-alpha+4
  angular_compiler: ^0.4.0-alpha+4
  firebase: ^4.3.1
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1
  sass_builder: ^1.1.2
  code_builder: ^3.0.0

dev_dependencies:
  pageloader: ^2.2.5
  webdriver: ^1.2.1
  build_runner: ^0.7.0
  build_web_compilers: ^0.2.0

dependency_overrides:
  # Necessary with angular: 5.0.0-alpha+1 dependency.
  analyzer: ^0.31.0-alpha.2

transformers:
- sass_builder
- angular:
      entry_points: web/main.dart
#- dart_to_js_script_rewriter

#- angular/transform/reflection_remover:
#    $include: test/**_test.dart
#- test/pub_serve:
#    $include: test/**_test.dart
#- dart_to_js_script_rewriter

#entry_points: web/main.dart

analyzer:
  strong-mode: true

builders:
  angular:
    options:
      use_new_template_parser: True

#web:
#   compiler:
#     debug: dartdevc